modLoader="javafml"
loaderVersion="${loaderVersionRange}"
license="${modLicense}"
[[mods]]
modId="malum"
version="${modVersion}"
displayName="${modName}"
authors="${modAuthors}"
description='''${modDescription}'''
[[dependencies.malum]]
modId="forge"
mandatory=true
versionRange="${forgeVersionRange}"
ordering="NONE"
side="BOTH"
[[dependencies.malum]]
modId="minecraft"
mandatory=true
versionRange="${minecraftVersionRange}"
ordering="NONE"
side="BOTH"
[[dependencies.malum]]
modId = "lodestone"
mandatory = true
versionRange = "[1.20.1-1.4.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.malum]]
modId = "curios"
mandatory = true
versionRange = "[5.7.0,)"
ordering = "NONE"
side = "BOTH"